### ISSUE TITLE
2021 Roadmap

### ISSUE THREAD

**Issue by nzbin** [ng-matero/ng-matero#76]
- [ ] **schematics:** generate component
- [x] add permission management and integrate `ngx-permissions`
- [x] refactor error page routes
- [ ] add reuse routing
- [x] replace `TSLint` with `ESLint`
- [x] update docs
- [x] add refresh token
